#! /bin/bash

mkdir $HOME/.config

for f in $(find -path "*" -not -path "./.git*" -not -path "./initScript" -not -path "./README.md" -not -path "." -not -path "./.config")
do
	#echo $f
	if [ -d $f ]
	then 
		mkdir $HOME$(echo $f| cut -c 2-)
	else
		ln -sf $(pwd)$(echo $f| cut -c 2-) $HOME$(echo $f| cut -c 2-)
	fi
	#echo ~$(echo $f| cut -c 2-)

done

